### ISSUE TITLE
Provide Python interface

### ISSUE THREAD

**Issue by dspechnikov** [dowjones/tokendito#1]
I generate MFA password for tokendito with python script and then pass it to the command line. It looks like this:

```bash
OTP=`python -c "import pyotp;print(pyotp.TOTP('${OKTA_2FA_SECRET}').now())"`

tokendito -u ${OKTA_USERNAME} -p ${OKTA_PASSWORD} --mfa-method=token:software:totp --mfa-response=${OTP}
```

So I already have a Python script but I still need bash to use the tool. I'd like to have Python interface to bypass shell scripting.

It could look like this:

```python
from tokendito import Tokendito

okta_authenticator = Tokendito(okta_tile_url, aws_profile, okta_username, okta_password, mfa_method)

# I could use AWS tokens right away without setting them locally if I need to
aws_tokens = okta_authenticator.get_aws_credentials(mfa_response)

# or just set them into local file as CLI does
okta_authenticator.set_local_credentials(aws_tokens)
```

Maybe there's better API, this just came out of my head.

**Comment by pcmxgti** [comment]
@dspechnikov given the nature of Tokendito, this approach is not something we are considering at this time. Thank you for the feedback!
