### ISSUE TITLE
Unable to retrieve 3-number challenge with okta push

### ISSUE THREAD

**Issue by tadcrazio** [dowjones/tokendito#107]
## Expected Behavior
When running tokendito after choosing push as the MFA method i switch to my device, accept the login, I am then prompted with a 3-number challenge.
I would expect tokendito to output the correct number in the challenge.

## Current Behavior
Unable to proceed with MFA as i have a 3 number challenge on my phone and no number to verify it against. 

## Possible Solution
Can only point to detail as to how the 3-number challenge with the API works:
https://developer.okta.com/docs/reference/api/authn/#response-example-waiting-for-3-number-verification-challenge-response

## Steps to Reproduce (for bugs)
I imagine this varies upon organization if they have this enabled or not. If enabled, authenticating from a new device and location likely will trigger the 3-number challenge.

1. run tokendito
2.choose push MFA
3.Accept the attempt on device to see a 3 number challenge

## Your Environment

WSL2 CentOS Linux release 7.9.2009 (Core) 
Python 3.6.8
tokendito 1.3.1

**Comment by pcmxgti** [comment]
Hi @tadcrazio, thank you for the report and link to the documentation. Tokendito currently doesn't support Number Challenge on push. We can definitely look into this as a future enhancement. Shortly after version 2.0, which is just around the corner.

**Comment by pcmxgti** [comment]
Hi @tadcrazio, I think that #109 implements what you asked about. We've tested this internally, but wanted to make sure this works for you if you don't mind giving this a whirl. There is a test build with this feature, you can install it with: `pip install -U --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple 'tokendito==2.1.0.dev20230124213936'`. There are a couple of more things going into `2.1.0`, but this should keep you going.

Please bear in mind that a lot of options, config, and command-line arguments have changed from version 1.3.x to version 2.0.

**Comment by tadcrazio** [comment]
@pcmxgti  Sorry for the delay, and thanks for working on that and getting back to me. I can't seem to find that index to test it out tho. "ERROR: No matching distribution found for tokendito==2.1.0.dev20230124213936"

**Comment by pcmxgti** [comment]
No worries, we all get busy from time to time. That package is only available on [https://test.pypi.org/project/tokendito/](https://test.pypi.org/project/tokendito/). Any 2.1.0.dev should work for testing, however, these are pre-release builds and may also be broken from time to time. We are hoping to wrap up 2.1 shortly, and this is already queued up.

**Comment by pcmxgti** [comment]
@tadcrazio we just released version 2.1.0 which should fix the issue you encountered.
