### ISSUE TITLE
Interactive prompt for AWS profile name

### ISSUE THREAD

**Issue by opis-mark** [dowjones/tokendito#110]
It would be nice to ask the user what name to give the AWS credential profile after the role is selected.  The prompt could be skipped if the env var `TOKENDITO_AWS_PROFILE` exists, the user config file contains a value for `aws_profile`, or the command line option `--aws-profile` is supplied.

Currently the AWS profile is defaulted to the IAM role name but this is not specific enough for my needs as I have access to multiple accounts with matching role names.  I prefix my profile names with the AWS account name so that I can have confidence that I am working in the correct environment.

For example, the way it works now is:
```
Waiting for an approval from the device...
User has been succesfully authenticated.
Discovering roles in 1 tile.

Please select one of the following:
[0] nonprod  arn:aws:iam::000000000000:role/read-only-role
[1] nonprod  arn:aws:iam::000000000000:role/read-write-role
[2] nonprod  arn:aws:iam::000000000000:role/admin-role
[3] prod  arn:aws:iam::111111111111:role/read-only-role
[4] prod  arn:aws:iam::111111111111:role/read-write-role
-> 3

Generated profile 'read-only-role' in /home/appuser/.aws/credentials.

Use profile to authenticate to AWS:
        aws --profile 'read-only-role' sts get-caller-identity
OR
        export AWS_PROFILE='read-only-role'

Credentials are valid until 2023-02-01 17:43:52+00:00 (2023-02-01 17:43:52 UTC).
```

And how I would like it to work is:
```
Waiting for an approval from the device...
User has been succesfully authenticated.
Discovering roles in 1 tile.

Please select one of the following:
[0] nonprod  arn:aws:iam::000000000000:role/read-only-role
[1] nonprod  arn:aws:iam::000000000000:role/read-write-role
[2] nonprod  arn:aws:iam::000000000000:role/admin-role
[3] prod  arn:aws:iam::111111111111:role/read-only-role
[4] prod  arn:aws:iam::111111111111:role/read-write-role
-> 3

Enter a profile name or leave blank to use 'read-only-role': prod_read-only-role

Generated profile 'prod_read-only-role' in /home/appuser/.aws/credentials.

Use profile to authenticate to AWS:
        aws --profile 'prod_read-only-role' sts get-caller-identity
OR
        export AWS_PROFILE='prod_read-only-role'

Credentials are valid until 2023-02-01 17:43:52+00:00 (2023-02-01 17:43:52 UTC).
```

**Comment by pcmxgti** [comment]
@opis-mark , this is an excellent suggestion. I think we should be able to implement this request fairly quickly for you.

**Comment by opis-mark** [comment]
Thanks @pcmxgti, I took a crack at it myself but I'm not sure I really unpacked the different ways configs are passed around properly.

**Comment by opis-mark** [comment]
I think I got it working actually.  This is my first time contributing to a public GitHub repo so please let me know if I've messed anything up and what I can do better next time.

**Comment by sevignyj** [comment]
https://github.com/dowjones/tokendito/pull/111 is merged to main and fixes this issue, thank you @opis-mark !
