### ISSUE TITLE
Failure when using custom time step size for TOTP code

### ISSUE THREAD

**Issue by CesarManriqueH** [dowjones/tokendito#29]
I'm generating TOTP codes using a custom time step size, like this:
`$(echo $OKTA_SEED | mintotp ${totp_time}`

It works fine when I set `totp_time` to 30 but I can't use another value because I get this error:
```
ERROR [okta_helpers.py:okta_verify_api_method():52]: Exiting due to Okta API error [E0000068]
Invalid Passcode/Answer
[{"errorSummary": "Your passcode doesn't match our records. Please try again."}]
```

Have you tried this before?
Do you know how to avoid this error?

Here's the like were I use tokendito:
```
tokendito -ou ${OKTA_APP_URL} -R ${AWS_ROLE_ARN} \
    --username ${OKTA_USER} --password ${OKTA_PASSWORD} \
    --mfa-method token:software:totp --mfa-response $(echo $OKTA_SEED | mintotp ${totp_time})
```

**Comment by mrchief** [comment]
@CesarManriqueH why was this closed?
