### ISSUE TITLE
CLI arguments are overridden with environment variables

### ISSUE THREAD

**Issue by dspechnikov** [dowjones/tokendito#5]
Tokendito prioritises environment variables over command-line arguments when getting parameters. 

This causes a lot of confusion ("hey, tokendito, I literally told you to use this username, why..."). Also, this is inconsistent with basically every CLI tool I used. They all give CLI arguments the highest priority (for example, [terraform](https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence)).

I think priority should be set depending on how "near" the parameter is to the CLI invokation. So priority should be in this order (from lowest to highest):
1. Environment variables
2. Configuration file (`okta_auth`)
3. CLI arguments

What do you think?

**Comment by pcmxgti** [comment]
@dspechnikov your approach makes sense to us.

There are other issues with passing environment variables. For instance, not all arguments can currently be passed through env(). We are addressing that with #4 . Once that fix is in place, we will be able to shuffle the order of operations to match your proposal. Our current thinking is that environment variables will have a separate namespace (e.g. `TOKENDITO_`). Once we implement we will add documentation as well, as requested in #6.

**Comment by pcmxgti** [comment]
@dspechnikov @mjrb this was fixed in the commit `fadc6f6` and documented in #94 . Please try it out and let us know if it works as expected.
