### ISSUE TITLE
Tokendito environment variables are not documented

### ISSUE THREAD

**Issue by dspechnikov** [dowjones/tokendito#6]
Tokendito uses `OKTA_` prefixed environment variables to get parameters alongside config file and CLI arguments.

I couldn't find a documentation about this. This affects user experience, so I think it should be documented.

**Comment by pcmxgti** [comment]
This was resolved in #103. I hope that the update and new documentation makes more sense now! This request was one of the main reasons why we set out to refactor Tokendito.
